### ISSUE TITLE
HTTP Scraping failed on Ubuntu torrent

### ISSUE THREAD

**Issue by tbunreal** [gallexis/pytorrent#19]
Hi, Downloading https://releases.ubuntu.com/21.10/ubuntu-21.10-desktop-amd64.iso.torrent gives this error.

```
ERROR:root:HTTP scraping failed: HTTPSConnectionPool(host='torrent.ubuntu.com', port=443): Max retries exceeded with url: /announce?info_hash=%F1%FC%DC%14b%D3e0%F5%26%C1%D9%40.%EC%91%00%B7%BA%18&peer_id=z%A7s%22%1E%B4%E1%DF%7F%ECR6%91%91%E3%24%A2%C6%3FO&uploaded=0&downloaded=0&port=6881&left=3116482560&event=started (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc7722b59d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
Traceback (most recent call last):
  File "/home/derrek/PycharmProjects/PyTorrent/venv/lib/python3.9/site-packages/urllib3/connection.py", line 174, in _new_conn
    conn = connection.create_connection(
  File "/home/derrek/PycharmProjects/PyTorrent/venv/lib/python3.9/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/derrek/PycharmProjects/PyTorrent/venv/lib/python3.9/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/derrek/PycharmProjects/PyTorrent/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 703, in urlopen
    httplib_response = self._make_request(
  File "/home/derrek/PycharmProjects/PyTorrent/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/derrek/PycharmProjects/PyTorrent/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/home/derrek/PycharmProjects/PyTorrent/venv/lib/python3.9/site-packages/urllib3/connection.py", line 358, in connect
    conn = self._new_conn()
  File "/home/derrek/PycharmProjects/PyTorrent/venv/lib/python3.9/site-packages/urllib3/connection.py", line 186, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fc7722b59d0>: Failed to establish a new connection: [Errno 101] Network is unreachable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/derrek/PycharmProjects/PyTorrent/venv/lib/python3.9/site-packages/requests/adapters.py", line 440, in send
    resp = conn.urlopen(
  File "/home/derrek/PycharmProjects/PyTorrent/venv/lib/python3.9/site-packages/urllib3/connectionpool.py", line 785, in urlopen
    retries = retries.increment(
  File "/home/derrek/PycharmProjects/PyTorrent/venv/lib/python3.9/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='torrent.ubuntu.com', port=443): Max retries exceeded with url: /announce?info_hash=%F1%FC%DC%14b%D3e0%F5%26%C1%D9%40.%EC%91%00%B7%BA%18&peer_id=z%A7s%22%1E%B4%E1%DF%7F%ECR6%91%91%E3%24%A2%C6%3FO&uploaded=0&downloaded=0&port=6881&left=3116482560&event=started (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc7722b59d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/derrek/PycharmProjects/PyTorrent/pytorrent/tracker.py", line 89, in http_scraper
    answer_tracker = requests.get(tracker, params=params, timeout=5)
  File "/home/derrek/PycharmProjects/PyTorrent/venv/lib/python3.9/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/home/derrek/PycharmProjects/PyTorrent/venv/lib/python3.9/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/home/derrek/PycharmProjects/PyTorrent/venv/lib/python3.9/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/derrek/PycharmProjects/PyTorrent/venv/lib/python3.9/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/derrek/PycharmProjects/PyTorrent/venv/lib/python3.9/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='torrent.ubuntu.com', port=443): Max retries exceeded with url: /announce?info_hash=%F1%FC%DC%14b%D3e0%F5%26%C1%D9%40.%EC%91%00%B7%BA%18&peer_id=z%A7s%22%1E%B4%E1%DF%7F%ECR6%91%91%E3%24%A2%C6%3FO&uploaded=0&downloaded=0&port=6881&left=3116482560&event=started (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fc7722b59d0>: Failed to establish a new connection: [Errno 101] Network is unreachable'))
ERROR:root:HTTP scraping failed: a bytes-like object is required, not 'list'
Traceback (most recent call last):
  File "/home/derrek/PycharmProjects/PyTorrent/pytorrent/tracker.py", line 103, in http_scraper
    ip = struct.unpack_from("!i", list_peers['peers'], offset)[0]
TypeError: a bytes-like object is required, not 'list'
```
 if you don't want to fix this, any way you can point me in the right direction?

**Comment by airswing** [comment]
#21 I was able to reproduce the error and address the issue in this PR.

**Comment by airswing** [comment]
This issue should probably be closed. @gallexis
